- hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - { role: itcraftsmanpl.php7 }
    - role: geerlingguy.postgresql
      become: yes
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.git }
    - geerlingguy.node
    - geerlingguy.composer
